CREATE OR REPLACE FUNCTION funcGetClient(p_email platform_client.email%TYPE) RETURN SYS_REFCURSOR
    IS
    cur_client    SYS_REFCURSOR;

BEGIN
    OPEN cur_client FOR
        SELECT D.USER_NAME, D.USER_PASSWORD, D.USER_EMAIL, A.PHONE_NUMBER, A.CREDITS, A.NIF, B.STREET, C.LONGITUDE, C.LATITUDE, C.ELEVATION,C.DESCRIPTION, B.CITY, B.PORT_NUMBER, B.ZIP_CODE
        FROM PLATFORM_CLIENT A, ADDRESS B, GEOGRAPHICAL_POINT C, PLATFORM_USER D
        WHERE A.LONGITUDE = B.LONGITUDE AND A.LATITUDE = B.LATITUDE AND B.LONGITUDE = C.LONGITUDE AND B.LATITUDE = C.LATITUDE AND D.USER_EMAIL = A.EMAIL AND A.EMAIL = p_email;
    RETURN cur_client;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20011, 'Client with email: ' || p_email || ' does not exist!');
        RETURN NULL;
END;